version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    environment:
      PHP_ENABLE_XDEBUG: 1
    networks:
      - net
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
  db:
    image: mariadb
    networks:
      - net
    container_name: yii2_db
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
networks:
  net:
    driver: bridge